Invite dev users to upgrade pip
This is required for psycopg-binary to install correctly.
As proposed in https://pypi.org/project/psycopg/3.0.9/

In old version of pip, the error look like:
ERROR: No matching distribution found for psycopg-binary==3.0.9; extra == "binary"