Let click ignore unknown options for 'pgbackrest' command
Previous implementation would fail when passing options to the
pgbackrest command because these were catched by click, e.g.:

  $ pglift pgbackrest -i main info --output=json
  [...]
  Error: No such option: --output